disabled_rules:
  - block_based_kvo
  - class_delegate_protocol
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - dynamic_inline
  - empty_enum_arguments
  - for_where
  - is_disjoint
  - large_tuple
  - legacy_hashing
  - line_length
  - multiple_closures_with_trailing_closure
  - no_fallthrough_only
  - private_over_fileprivate
  - private_unit_test
  - redundant_objc_attribute
  - redundant_set_access_control
  - superfluous_disable_command
  - todo
  - trailing_whitespace
  - trailing_newline
  - unused_control_flow_label
  - valid_ibinspectable
  - vertical_whitespace
  - xctfail_message
  

opt_in_rules:
  - closure_body_length
#  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collction
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_self
  - fatal_error_message
  - file_name_no_space
  - function_default_parameter_at_end
  - identical_operands
  - implicitly_unwrapped_optional
#  - indentation_width
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  -

excluded:
  - Pods
  - DaangnMarket/AppDelegate.swift
  - DaangnMarket/SceneDelegate.swift
  - DaangnMarket/InitialStart/Model/TownInfo.swift
  - DaangnMarket/Test
  - DaangnMarket/Common/Extensions
