# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DaangnMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaangnMarket
  pod 'Then'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'SwiftLint'

  pod 'Firebase/Analytics'  
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
end
